main/urls.py
from django.urls import path, include
from .views import main, students, teacher
urlpatterns = [
    path('', main.home, name='home'),

    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('courses/', students.StudentCoursesView.as_view(), name='student_courses'),
        path('quiz/<int:pk>/student/results/', students.QuizResultsView.as_view(), name='student_quiz_results'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
        path('list/', students.StudentList.as_view(), name='student_list')
    ], 'main'), namespace='students')),

    path('teachers/', include(([
        path('', teacher.QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/', teacher.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teacher.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', teacher.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', teacher.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', teacher.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teacher.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teacher.QuestionDeleteView.as_view(),
             name='question_delete'),
    ], 'main'), namespace='teachers')),
]

quiz_app/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import main, students, teacher

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', main.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teacher.TeacherSignUpView.as_view(), name='teacher_signup')
]

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError
from .models import User, Answer, Student, Question, StudentAnswer, Subject


class TeacherSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_teacher = True
        if commit:
            user.save()
        return user


class StudentSignUpForm(UserCreationForm):
    courses = forms.ModelMultipleChoiceField(queryset=Subject.objects.all(),
                                             widget=forms.CheckboxSelectMultiple, required=True)

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.courses.add(*self.cleaned_data.get('courses'))
        return user


class StudentCoursesForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['courses']
        widgets = {'courses': forms.CheckboxSelectMultiple}


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text']


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one correct answer', code='no_correct_answer')


class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(queryset=Answer.objects.none(),
                                    widget=forms.RadioSelect(), required=True, empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ['answer']

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')

main/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Count, Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, ListView
from django.views import View
from ..decorators import student_required
from ..forms import StudentSignUpForm, StudentCoursesForm, TakeQuizForm
from ..models import Student, Quiz, Question, TakenQuiz

User = get_user_model()


class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:quiz_list')


@method_decorator([login_required, student_required], name='dispatch')
class StudentCoursesView(UpdateView):
    model = Student
    form_class = StudentCoursesForm
    template_name = 'main/students/courses_form.html'
    success_url = reverse_lazy('students:quiz_list')

    def get_object(self, queryset=None):
        return self.request.user.student

    def form_valid(self, form):
        messages.success(self.request, 'Courses have been updated')
        return super().form_valid(form)


@method_decorator([login_required, student_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ['name']
    context_object_name = 'quizzes'
    template_name = 'main/students/quiz_list.html'

    def get_queryset(self):
        student = self.request.user.student
        taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.exclude(pk__in=taken_quizzes).annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['student_subjects'] = self.request.user.student.courses.values_list('pk', flat=True)
        return context


@method_decorator([login_required, student_required], name='dispatch')
class QuizResultsView(View):
    template_name = 'main/students/quiz_result.html'

    def get(self, request, *args, **kwargs):
        quiz = Quiz.objects.get(id=kwargs['pk'])
        taken_quiz = TakenQuiz.objects.filter(student=request.user.student, quiz=quiz)
        if not taken_quiz:
            return render(request, 'main/404.html')
        questions = Question.objects.filter(quiz=quiz)
        context = {
            'questions': questions,
            'quiz': quiz,
            'percentage': taken_quiz[0].percentage
        }
        return render(request, self.template_name, context)


@method_decorator([login_required, student_required], name='dispatch')
class TakenQuizListView(ListView):
    model = TakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'main/students/taken_quiz_list.html'

    def get_queryset(self):
        queryset = self.request.user.student.taken_quizzes \
            .select_related('quiz', 'quiz__subject') \
            .order_by('quiz__name')
        return queryset


@login_required
@student_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    student = request.user.student
    if student.quizzes.filter(pk=pk).exists():
        return render(request, 'main/students/taken_quiz_list.html')

    total_questions = quiz.questions.count()
    unanswered_questions = student.get_unanswered_questions(quiz)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
    question = unanswered_questions.first()

    if request.method == 'POST':
        form = TakeQuizForm(question=question, data=request.POST)
        if form.is_valid():
            with transaction.atomic():
                student_answer = form.save(commit=False)
                student_answer.student = student
                student_answer.save()
                if student.get_unanswered_questions(quiz).exists():
                    return redirect('students:take_quiz', pk)
                else:
                    correct_answers = student.quiz_answers.filter(
                        answer__question__quiz=quiz, answer__is_correct=True).count()
                    percentage = round((correct_answers / total_questions) * 100.0, 2)
                    TakenQuiz.objects.create(student=student, quiz=quiz, score=correct_answers, percentage=percentage)
                    student.score = TakenQuiz.objects.filter(student=student).aggregate(Sum('score'))['score__sum']
                    student.save()
                    messages.success(request, 'Your score for the quiz %s is %s' % (quiz.name, percentage))
                    return redirect('students:student_quiz_results', pk)
    else:
        form = TakeQuizForm(question=question)
    context = {
        'form': form,
        'quiz': quiz,
        'question': question,
        'progress': progress,
        'answered_questions': total_questions - total_unanswered_questions,
        'total_questions': total_questions
    }
    return render(request, 'main/students/take_quiz_form.html', context)


@method_decorator([login_required, student_required], name='dispatch')
class StudentList(ListView):
    model = Student
    template_name = 'main/students/student_list.html'
    context_object_name = 'students'

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        queryset = Student.objects.order_by('-score')
        if query:
            queryset = queryset.filter(user__username__icontains=query)
        return queryset

main/views/teacher.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Avg, Count
from django.shortcuts import get_object_or_404, redirect, render
from django.forms import inlineformset_factory
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from ..decorators import teacher_required
from ..forms import TeacherSignUpForm, QuestionForm, BaseAnswerInlineFormSet
from ..models import Question, Quiz, Answer

User = get_user_model()


class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('teachers:quiz_change_list')


@method_decorator([login_required, teacher_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ['name']
    context_object_name = 'quizzes'
    template_name = 'main/teachers/quiz_change_list.html'

    def get_queryset(self):
        queryset = self.request.user.quizzes.select_related('subject'). \
            annotate(questions_count=Count('questions', distinct=True)). \
            annotate(taken_count=Count('taken_quizzes', distinct=True))
        return queryset


@method_decorator([login_required, teacher_required], name='dispatch')
class QuizCreateView(CreateView):
    model = Quiz
    fields = ['name', 'subject']
    template_name = 'main/teachers/quiz_add_form.html'

    def form_valid(self, form):
        quiz = form.save(commit=False)
        quiz.owner = self.request.user
        quiz.save()
        messages.success(self.request, 'Quiz has been created. You can add questions')
        return redirect('teachers:quiz_change', quiz.pk)


@method_decorator([login_required, teacher_required], name='dispatch')
class QuizUpdateView(UpdateView):
    model = Quiz
    fields = ['name', 'subject']
    context_object_name = 'quiz'
    template_name = 'main/teachers/quiz_change_form.html'

    def get_context_data(self, **kwargs):
        kwargs['questions'] = self.get_object().questions.annotate(answers_count=Count('answers'))
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()

    def get_success_url(self):
        return reverse('teachers:quiz_change', kwargs={'pk': self.object.pk})


@method_decorator([login_required, teacher_required], name='dispatch')
class QuizDeleteView(DeleteView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'main/teachers/quiz_delete.html'
    success_url = reverse_lazy('teachers:quiz_change_list')

    def delete(self, request, *args, **kwargs):
        quiz = self.get_object()
        messages.success(request, 'The quiz %s has been deleted' % quiz.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()


@method_decorator([login_required, teacher_required], name='dispatch')
class QuizResultsView(DetailView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'main/teachers/quiz_results.html'

    def get_context_data(self, **kwargs):
        quiz = self.get_object()
        taken_quizzes = quiz.taken_quizzes.select_related('student__user').order_by('-date')
        total_taken_quizzes = taken_quizzes.count()
        quiz_score = quiz.taken_quizzes.aggregate(average_score=Avg('score'))
        extra_context = {
            'taken_quizzes': taken_quizzes,
            'total_taken_quizzes': total_taken_quizzes,
            'quiz_score': quiz_score
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()


@login_required
@teacher_required
def question_add(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk, owner=request.user)
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            messages.success(request, 'You can now add options for the question')
            return redirect('teachers:question_change', quiz.pk, question.pk)
    else:
        form = QuestionForm()
    context = {
        'form': form,
        'quiz': quiz
    }
    return render(request, 'main/teachers/question_add_form.html', context)


@login_required
@teacher_required
def question_change(request, quiz_pk, question_pk):
    quiz = get_object_or_404(Quiz, pk=quiz_pk, owner=request.user)
    question = get_object_or_404(Question, pk=question_pk, quiz=quiz)
    AnswerFormSet = inlineformset_factory(
        Question,
        Answer,
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'),
        min_num=2,
        validate_min=True,
        max_num=5,
        validate_max=True
    )
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, 'Question and answers have been saved')
            return redirect('teachers:quiz_change', quiz.pk)
    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)
    context = {
        'quiz': quiz,
        'question': question,
        'form': form,
        'formset': formset
    }
    return render(request, 'main/teachers/question_change_form.html', context)


@method_decorator([login_required, teacher_required], name='dispatch')
class QuestionDeleteView(DeleteView):
    model = Question
    context_object_name = 'question'
    template_name = 'main/teachers/question_delete.html'
    pk_url_kwarg = 'question_pk'

    def get_context_data(self, **kwargs):
        question = self.get_object()
        kwargs['quiz'] = question.quiz
        return super().get_context_data(**kwargs)

    def delete(self, request, *args, **kwargs):
        question = self.get_object()
        messages.success(request, 'The question %s has been deleted' % question.text)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return Question.objects.filter(quiz__owner=self.request.user)

    def get_success_url(self):
        question = self.get_object()
        return reverse('teachers:quiz_change', kwargs={'pk': question.quiz_id})

main/templates/main/students/courses_form.html
{% extends 'main/base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
  <h2 class="mb-3">Update your Courses</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">Cancel</a>
  </form>
{% endblock %}

main/templates/main/students/header.html
<h2>Quiz</h2>


<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'students:quiz_list' %}">New</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'students:taken_quiz_list' %}">Taken</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'students' %} active{% endif %}" href="{% url 'students:student_list' %}">Students</a>
  </li>
</ul>

main/templates/main/students/quiz_list.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'main/datatables/dataTables.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
  {% include 'main/students/header.html' with active='new' %}
  <p class="text-muted">
    Subjects:{% for subject in user.student.courses.all %} {{ subject }}{% endfor %}
    <a href="{% url 'students:student_courses' %}"><small>(update courses)</small></a>
  </p>

  <table class="table table-bordered mb-0" id="#" >
    <thead>
      <tr>
        <th>Quiz</th>
        <th class="d-none d-sm-table-cell">Subject</th>
        <th class="d-none d-sm-table-cell">Questions</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for quiz in quizzes %}
        <tr{% if quiz.subject.id in student_subjects %} style="background: lightgrey"{%endif%}>
          <td class="align-middle">{{ quiz.name }}</td>
          <td class="align-middle d-none d-sm-table-cell">{{ quiz.subject }}</td>
          <td class="align-middle d-none d-sm-table-cell">{{ quiz.questions_count }}</td>
          <td class="text-right" data-orderable="false">
            <a href="{% url 'students:take_quiz' quiz.pk %}" class="btn btn-primary">Start quiz</a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td class="bg-light text-center font-italic" colspan="4">No quiz matching your course right now.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block js %}
<script src="{% static 'main/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'main/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'main/datatables/dataTables.bootstrap4.min.js' %}"></script>
{% endblock %}

main/templates/main/students/quiz_result.html
{% extends 'main/base.html' %}
{% block content %}
    {% load quiz_extras %}
{% include 'main/students/header.html' with active='taken' %}

<h2>{{quiz.name}}</h2>
{{ quiz.subject }}

<div class="progress">
  <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: {{percentage}}%" aria-valuenow="{{percentage}}" aria-valuemin="0" aria-valuemax="100">{{percentage}}%</div>
</div><br>
{% for question in questions %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{forloop.counter}}. {{question.text}}</h5>
    <table class="table table-bordered table-sm">
      <thead><tr><th>Yours</th><th>Correct</th><th></th></tr></thead>
      <tbody>
        {% for opt in question.answers.all %}
        {% marked_answer user opt as opt_marked %}
        <tr>
          <td style="width: 100px;{% if opt_marked == 'correct' %} background:green{% elif opt_marked == 'wrong' %} background:red{% endif %}"> </td>
          <td style="width: 100px;{% if opt.is_correct %} background:green{% endif %}"></td>
          <td>{{opt.text}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<br>
{% endfor %}
{% endblock %}

main/templates/main/students/student_list.html
{% extends 'main/base.html' %}
{% load quiz_extras %}

{% block css %}
<style type="text/css">
  .media {
    margin-top: 10px
  }
</style>
{% endblock %}

{% block content %}
  {% include 'main/students/header.html' with active='students' %}
<form method='GET'>
  <div class="row">
    <div class="col-sm-6">
      <div class="input-group mb-3">
        <input type="text" class="form-control" name='q' value='{{ request.GET.q }}' placeholder="search">
        <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="submit">Search</button>
        </div>
      </div>
    </div>
  </div>
</form>
<br>
<div class="row">
{% for student in students %}
  <div class="col-sm-3">
    <div class="media">
      <a>
        <img class="mr-3" src="{{ student.user.username }}" alt="{{ student.user.get_full_name }}">
      </a>
      <div class="media-body" style="font-size: 12px">
        {{ student.user.get_full_name }}
          {{ student.user.username }}<br>
        <strong>{{ student.score }}</strong><br>
{#        {{ student.taken_quizzes.all|top_subject }}#}
      </div>
    </div>
  </div>
{% empty %}
  <div class="col-sm-6"><p>No student matched your search.</p></div>
{% endfor %}
</div>
{% endblock %}

main/templates/main/students/take_quiz_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block css %}
<style type="text/css">
/* https://jsbin.com/zequb/7/edit */
input[type=radio]{
  /* hide original inputs */
  visibility: hidden;
  position: absolute;
}
input[type=radio] + label{
  cursor:pointer;
}
input[type=radio] + label:before{
  width:16px;
  height:16px;
  content: " ";
  display:inline-block;
  border:1px solid #ccc;
  border-radius:50%;
  box-shadow: inset 0 -3px 6px #e4e4e4;
  transition: 0.3s;
}

/* CHECKED */
input[type=radio]:checked + label:before{
  box-shadow: inset 0 0 0 5px #2196F3;
}
</style>
{% endblock %}

{% block content %}
  <div class="progress mb-3">
    <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
  </div>
  <h2><span class="badge badge-secondary">{{ answered_questions|add:"1" }}/{{total_questions}}</span></h2>

  <h2 class="mb-3">{{ quiz.name }}</h2>
  <p class="lead">{{ question.text }}</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Next →</button>
  </form>
{% endblock %}

main/templates/main/students/taken_quiz_list.html
{% extends 'main/base.html' %}

{% block content %}
  {% include 'main/students/header.html' with active='taken' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>%</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_quiz in taken_quizzes %}
          <tr>
            <td><a href="{% url 'students:student_quiz_results' taken_quiz.quiz.id %}">{{ taken_quiz.quiz.name }}</a></td>
            <td>{{ taken_quiz.quiz.subject }}</td>
            <td>{{ taken_quiz.percentage }}</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">You haven't completed any quiz yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}